// 更新播放列表
export const UPDATE_MUSICLIST = 'UPDATE_MUSICLIST'
export const UPDATE_PLAYLIST = 'UPDATE_PLAYLIST'
export const UPDATE_CURMUSIC = 'UPDATE_CURMUSIC'
export const UPDATE_PREVMUSIC = 'UPDATE_PREVMUSIC'

// 切换音乐播放暂停
export const UPDATE_MUSICPLAY = 'UPDATE_MUSICPLAY'
// 切换音乐
export const UPDATE_MUSIC = 'UPDATE_MUSIC'
// 更新播放总时长
export const UPDATE_MUSICTOTALTIME = 'UPDATE_MUSICTOTALTIME'
// 更新播放状态
export const UPDATE_MUSICSTATUS = 'UPDATE_MUSICSTATUS'
// 更新播放当前时间
export const UPDATE_MUSICCURRENTTIME = 'UPDATE_MUSICCURRENTTIME'
// 更新已缓冲时长
export const UPDATE_MUSICBUFFERTIME = 'UPDATE_MUSICBUFFERTIME'
// 更新播放进度
export const UPDATE_MUSICFASTSEEK = 'UPDATE_MUSICFASTSEEK'
// 更新缓冲状态
export const UPDATE_MUSICLOADING = 'UPDATE_MUSICLOADING'
// 更新下架状态
export const UPDATE_MUSICOFF = 'UPDATE_MUSICOFF'
